import os
import json
import re

def structure_summary_table(text_path, output_json_path):
    """
    Parses the summary table from the extracted text and saves it as a JSON file.
    """
    print(f"Reading raw text from: {text_path}")
    try:
        with open(text_path, 'r', encoding='utf-8') as f:
            full_text = f.read()
    except FileNotFoundError:
        print(f"ERROR: The file {text_path} was not found.")
        print("Please make sure you have run extractor.py and the output files are in the correct directory.")
        return

    # Isolate the text of the summary table for more accurate parsing
    summary_table_match = re.search(r"SUMMARY TABLE\s*(.*)", full_text, re.DOTALL)
    
    if not summary_table_match:
        print("ERROR: Could not find 'SUMMARY TABLE' in the text. Cannot proceed.")
        return

    table_text = summary_table_match.group(1)

    # This regex is designed to find each record in the summary table.
    # It looks for a pattern like: [Number] [Impacted Text] [Number.Number] [Exposed Text]
    # and handles multi-line descriptions.
    pattern = re.compile(
        r"^\s*(\d+)\s*\n(.*?)\n\s*(\d+\.\d+)\s*\n(.*?)(?=\n\s*\d+\s*\n|\Z)", 
        re.MULTILINE | re.DOTALL
    )
    
    records = []
    for match in pattern.finditer(table_text):
        point_no, impacted_text, _, exposed_text = match.groups()
        
        # Clean up the captured text by replacing newlines and extra spaces
        impacted_text_clean = re.sub(r'\s+', ' ', impacted_text.strip())
        exposed_text_clean = re.sub(r'\s+', ' ', exposed_text.strip())
        
        record = {
            "id": int(point_no),
            "impacted_area_observation": impacted_text_clean,
            "probable_root_cause": exposed_text_clean,
            "photos": {
                "observation_photos": [],
                "root_cause_photos": []
            },
            "thermal_data": None
        }
        records.append(record)

    if not records:
        print("WARNING: Could not extract any records from the summary table.")
        print("Check the format of 'full_text.txt' to ensure the summary table is present.")
        return

    # Ensure the output directory exists
    output_dir = os.path.dirname(output_json_path)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Save the structured data to a JSON file
    with open(output_json_path, 'w', encoding='utf-8') as f:
        json.dump(records, f, indent=4)

    print(f"\nSuccess! Structured data saved to {output_json_path}")
    print(f"Extracted {len(records)} records from the summary table.")


if __name__ == "__main__":
    # Path to the text file generated by extractor.py
    input_text_file = os.path.join("output", "sample_report_data", "full_text.txt")
    
    # Path for our new structured JSON output
    output_json_file = os.path.join("output", "structured_report.json")

    structure_summary_table(input_text_file, output_json_file)
